services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    networks:
      - default
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8000:8000"
    restart: always

networks:
  default:
    driver: bridge
